name = "SNaQ"
uuid = "c2bf7a07-44d2-4d11-b5e2-76dc5aa199d6"
authors = ["Claudia Solis-Lemus <crsl4@users.noreply.github.com>", "Paul Bastide <pbastide@users.noreply.github.com>", "Cecile Ane <cecileane@users.noreply.github.com>", "and contributors"]
version = "0.1.0"

[compat]
julia = "1.5"
