[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
PhyloNetworks = "33ad39ac-ed31-50eb-9b15-43d0656eaa72"
SNaQ = "c2bf7a07-44d2-4d11-b5e2-76dc5aa199d6"

[sources.PhyloNetworks]
rev = "dev"
url = "https://github.com/JuliaPhylo/PhyloNetworks.jl"
